server:
  port: 8080

spring:

  config:
    import: "optional:file:.env[.properties]"

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    show-sql: false 
    properties:
      hibernate.format_sql: true

concept:
  api:
    cnpj: ${CONCEPT_CNPJ}
    senhaCliente: ${CONCEPT_SENHA_CLIENTE}
    senhaCentral: ${CONCEPT_SENHA_CENTRAL}
    endpoints:
      automatizador: "http://52.6.27.50:8181/automatizador"
      importador: "http://52.6.27.50:8181/importadorPedidos"
  
  automation:
    interval: ${CONCEPT_AUTOMATION_INTERVAL:60000}